import { BottomNav } from "@/components/bottom-nav";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "D'Ultima Hora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body
        className={` antialiased bg-white overflow-x-hidden` }
      >
          <main className="pb-12 md:pb-0">
            {children}
          </main>
        <BottomNav/>
      </body>
    </html>
  );
}
