import { BottomNav } from "@/components/bottom-nav";
import { TermsBanner } from "@/components/term-banner";
import { Footer } from "@/components/footer";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "D'Ultima Hora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body
        className={` antialiased bg-white overflow-x-hidden` }
      >
          <main className="pb-12 md:pb-0">
            {children}
        </main>
        <TermsBanner />
        <Footer />
        <BottomNav/>
      </body>
    </html>
  );
}
